name: Python CI

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8 (optional)
        run: |
          pip install flake8
          flake8 .

      - name: Run Flask with mocked Ollama
        run: |
         export CI=true
         python app.py &
         sleep 5
         curl -f http://localhost:5001/generer-pdf || echo "skip if no body"
